development:
  adapter: postgresql
  database: bill_splitter_development
  username: postgres
  password: postgres
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: bill_splitter_production
  host: localhost
  pool: 5
  timeout: 5000